### ISSUE TITLE
"ganache-cli -e" throws Error: while converting number to string

### ISSUE THREAD

**Issue by bharatbiswal** [ConsenSys-archive/ganache-cli-archive#500]
$ ganache-cli -e

Error: while converting number to string, invalid number value 'true', should be a number matching (^-?[0-9.]+).
    at d (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:1537966)
    at Object.toWei (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:1538769)
    at Object.toWei (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:100396)
    at StateManager.initialize (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:4070602)
    at new s (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:4081531)
    at new l (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:675554)
    at Object.create (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:726161)
    at Object.server (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:4254180)
    at Object.<anonymous> (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:4348478)
    at a (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:110)
    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:524
    at Object.<anonymous> (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:536)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

**Comment by mikeseese** [comment]
Thanks for reporting this! This must have gotten fixed in one of the versions since this was reported, try using the latest version of ganache-cli.

Thanks!

**Comment by einaralex** [comment]
I'm using the newest version (6.1.6) and I'm still getting this error, also when using -acctKeys.
