### ISSUE TITLE
Incorrect block number in ganache-cli 6.4.4

### ISSUE THREAD

**Issue by barakman** [ConsenSys-archive/ganache-cli-archive#667]
## Expected Behavior

`web3.eth.blockNumber` should be equal to the actual (on-chain) `block.number`.

## Current Behavior

`web3.eth.blockNumber` is equal to `block.number - 1`.

## Possible Solution

This problem seems to have been fixed in ganache-cli 6.5.1.

I would be happy to understand what the problem was and how it was fixed (or to get a reference to the relevant release note, if viable).

## Steps to Reproduce

File `package.json`:
```
  "dependencies": {
    "ganache-cli": "6.4.4",
    "truffle": "4.1.14"
  }
```
File `MyContract.sol`:
```
pragma solidity 0.4.24;
contract MyContract {
    function get() public view returns (uint256) {
        return block.number;
    }
}
```
File `MyContractTest.js`:
```
contract("MyContractTest", function(accounts) {
    it("test", async function() {
        const MyContract = await artifacts.require("MyContract").new();
        const expected = web3.eth.blockNumber;
        const actual = await MyContract.get();
        console.log();
        console.log("expected:", expected);
        console.log("actual:", actual.toString());
    });
});
```
Execution:
1. Run `ganache-cli`
2. Run `truffle test`

Printout:
```
expected: 1
actual: 2
```
When switching to ganache-cli 6.5.1, the printout is:
```
expected: 1
actual: 1
```

## My Environment
* Ganache Version: 6.4.4
* Truffle Version: 4.1.14
* NodeJS Version: 10.16.0 (npm 6.9.0)
* Operating System: Windows 10 64 bits

**Comment by davidmurdoch** [comment]
This was fixed by https://github.com/trufflesuite/ganache-core/pull/443 referenced in the release notes for [6.5.1](https://github.com/trufflesuite/ganache-cli/releases/tag/v6.5.1#user-content-v6.5.1-Changelog).

Is there any reason you can't update to 6.5.1?

**Comment by barakman** [comment]
@davidmurdoch:

There was a reason until recently - updating to 6.5.1 would yield exactly one of the following:
- If I didn't fix my test to comply with the new version, then `truffle test` would fail
- If I did fix my test to comply with the new version, then `solidity-coverage` would fail

I reported this problem at https://github.com/sc-forks/solidity-coverage/issues/362 as well, and the dev team fixed it almost instantly!

Thanks :)

One thing to notice - I would take the liberty to guess that if this fix in `ganahe-cli` has broken my test, then it has probably broken many other tests which rely on this specific behavior (`web3.eth.blockNumber == block.number - 1`).

Perhaps adding a very explicit announcement (or warning if you will) on the release notes of both 6.4.4 and 6.5.1 would be useful here (though I admit I haven't actually made sure that it isn't already there).
