### ISSUE TITLE
Apparently Wrong Event implementation

### ISSUE THREAD

**Issue by IamSandipC** [ConsenSys-archive/ganache-cli-archive#74]
Following are the issues I see with Test RPC. Please correct me if I am wrong.

Currently when
1. Event is watched it does not populate all the past events based on filter option.
2. calling get does not fire watch
3. calling get clears the event logs. 2nd call does not return anything.

**Comment by IamSandipC** [comment]
On further investigation..looks like get() calls eth_getFilterChanges. It should call eth_getLogs or eth_getFilterLogs. Only poll will call eth_getFilterChanges and it will fire all the callbacks registered.

**Comment by tcoulter** [comment]
@IamSandipC Can you provide code to expose these errors? My first reaction is that this is normal behavior for the web3 library. Can you explain how your experience differs from geth?

From my initial reaction, I'd say:
1. I believe this is default behavior.
2. I'm not sure what this means, unfortunately.
3. This is normal behavior.

**Comment by IamSandipC** [comment]
Sure... I will give full details....
point 2 means: If I am watching an event with a callback and just call get() on same event just after the transaction is added to the block (with event), the watch callback is not fired..

**Comment by IamSandipC** [comment]
Between ... here is the documentation from json rpc:

eth_getFilterLogs
Returns an array of all logs matching filter with given id.

eth_getFilterChanges
Polling method for a filter, which returns an array of logs which occurred **since last poll.**

and javascript API documentation says:
// would get all past logs again.
var myResults = myEvent.get(function(error, logs){ ... });

Further looking at the code of web3 what I see whenever and event is attached (#1 above) or get(3# above), eth_getFilterLogs is called and if filter option is matching something (say fromBlock:0, toBlok:'latest'). Then it will give everything. So multiple get() call will repeat the result.

Whereas, after initial watch call, web3 keeps polling and calls eth_getFilterChanges and gets only new update..

I will create detail test cases and get back to you soon with result getH vs testrpc..

**Comment by jeremyellis** [comment]
I believe this issue is related: https://github.com/ethereumjs/testrpc/issues/50

**Comment by IamSandipC** [comment]
@tcoulter Here are the details of how to check it. Sorry about the delay.
Steps:
1. Created a simple contract:

```
contract TestEvent {
    uint counter;
    event Print(uint i);

    function TestEvent() {
        counter=0;
    }

    function Count() {
        counter +=1;
        Print(counter);
    }

}
```
1. Deployed it to both test-rpc and geth private network.
2. called the Count() method *_5 times *_ against each network using web3 js. 

```
testEvent.Count.sendTransaction({from:"0x5c1c6d4befc3a9f25941943dfc387709829728a5"})
```
1. Next created the event.

```
var eve = testEvent.Print(null,{fromBlock:0, toBlock:'latest'});
```
1. Next, wrote a helper method to call the get() method 3 times consecutively.

```
var callGet= function(num){
         eve.get(function(err,logs){
              console.log("got for" + num);
              logs.map(function(log){console.log(log.args.i.valueOf()); });
             });
     };

for(var i=1;i<4;i++){callGet(i);}
```
1. Here is the **RESULT**
   For, test RPC (no log is retrieved and written)

```
    got for1
    got for2
    got for3
```

For geth (all the logs are fetched **every time**  get() is called and have not been cleared. 

```
got for1
1
2
3
4
5
got for2
1
2
3
4
5
got for3
1
2
3
4
5
```
1. Next called the Count() method once more and for loop again

```
testEvent.Count.sendTransaction({from:"0x5c1c6d4befc3a9f25941943dfc387709829728a5"})
for(var i=1;i<4;i++){callGet(i);}
```

This time test-rpc returns only the **last *_log and only for the *_first get call**

```
got for1
6
got for2
got for3
```

geth returns all of them again from the beginning for all get() call

```
got for1
1
2
3
4
5
6
got for2
1
2
3
4
5
6
got for3
1
2
3
4
5
6

```

Hope this explains all of the three points I mentioned before.

**Comment by tcoulter** [comment]
This should have been fixed here: https://github.com/ethereumjs/testrpc/commit/6c184014a59516f876332a01cbbf8b4fe80f7e7c

Please reopen if it is not. Cheers!

**Comment by tcoulter** [comment]
Hmm, perhaps I'm wrong about this being fixed. Can you recheck to be sure?

**Comment by jeremyellis** [comment]
Still doesn't seem to work for me; just keep getting an empty array.

Are the logs being added to the array correctly here? https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain.js#L644
